name: Run Embedding SDK Storybook
runs:
  using: "composite"
  steps:
    - name: Prepare frontend environment
      uses: ./.github/actions/prepare-frontend

    - name: Prepare back-end environment
      uses: ./.github/actions/prepare-backend
      with:
        m2-cache-key: "cljs"

    - name: Compile CLJS
      run: yarn build-pure:cljs
      shell: bash


    - name: Wait for Storybook to become available
      run: |
        echo "Waiting for Storybook to be served..."
        while ! curl --silent --fail http://localhost:6006; do
          sleep 5
          echo "Retrying..."
        done
        echo "Storybook is being served!"
      shell: bash
